### PR TITLE
Merge With Siutsch update to 1.49

### PR DESCRIPTION
**Pull request by Trevelopment**
Marge Across Forks.

### CODE REVIEW

**Comment by Siutsch** [comment]
Hi.
I am not that familiar with that github thing, it's new to me.
I don't know, how to merge your changes here, but I added your tweak in new version V1.49.

**Comment by Trevelopment** [comment]
Hi,

I am somewhat new to GitHub as well.  I was trying to open a pull 
request to myself across forks to merge your changes onto my fork but 
accidentally did the other way around.  I did enjoy contributing to AIO 
tweaks and plan to code more improvements in the future.  PS. my video 
player v2 stopped working with the your version I tested (1.49) any idea 
why that might happen?

- Trevor Martin

-- 
------------------------------------------------------------------------
Trevor G Martin
Chief Technology Officer
Screenbid.com <http://screen.bid/Trez>
8569 Higuera Street
Culver City, California 90232

------------------------------------------------------------------------

**Comment by Siutsch** [comment]
Ah, you can do it this way too (fork). That was new to me too. :)

Videoplayer V2 by vic_bam85 hasn't changed for some time, so I don't know, why it stopped working.

Here it works, but only sometimes, not always, I hope vic_bam85 will improve it.

If you wanna use eMail, then with: zeuch@gmx.de

Marcus.

**Comment by Trevelopment** [comment]
Thank you, I will look over the code and see if i can find anything to 
improve as well.

- Trez

-- 
------------------------------------------------------------------------
Trevor G Martin
Chief Technology Officer
Screenbid.com <http://screen.bid/Trez>
8569 Higuera Street
Culver City, California 90232
------------------------------------------------------------------------

**Pull request closed without merging**
