### PR TITLE
README & FAQ Markdown.

### PR DESCRIPTION
**Pull request by Trevelopment**
Created README.md and AIO-FAQ.md from AIO_README.txt and AIO_FAQ.txt.  Uses GitHub Flavored Markdown for better readability.

### CODE REVIEW

**Comment by Siutsch** [comment]
Hi.
Can you shortly explain, how you made the md files out of the txt files?
Is there an automatic way to do that?

**Comment by Trevelopment** [comment]
Hi Marcus,

I don't know your background in web design but markdown is very easy to 
pick up.  It has very simple syntax, regular html headings such as h1, 
h2, h3, bold, italics etc. are done like this:

# h1
## h2
### h3
#### h4  (goes to h6)
**bold** or __bold__
*italics* or _italic_
 > Quote
* list item or - li
[Link](http://mazdatweaks.com "Mazda AIO Tweaks")
*** or ___  is <hr> (horizontal line)

You can use this tool to turn txt into md files: http://dillinger.io 
<http://dillinger.io/>. You just need to add your own markdown and it 
shows you the output.  It starts you off with an example md file so I'm 
guessing 5-10 minutes of playing around with it and you will begin to 
understand. There is also this link from the Dillinger menu: 
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet.

And for mazdatweaks.com <http://mazdatweaks.com>, I have a little bit of 
your translated German (now you can switch between German and English 
with the buttons on top) if you would like to have more translated you 
can wrap it in a <div class="german"></div> and it will be included with 
the German translation.  Or you can just add it to the README.md because 
I'm using that file within the page to create the main content.
Any other ideas/content you want up there just let me know, I made that 
site for you to show off your skills. I can also make you an 
@mazdatweaks.com email that will forward to your regular email... if you 
want.

One more thing, I never got my CMU out of the incomplete boot, do you 
think this is a good idea (or know anyone else who has done this): 
http://mazda3revolution.com/forums/2014-2016-mazda-3-skyactiv-audio-electronics/57714-infotainment-project-515.html#post1631825 
or am I better off just pinging the dealer for a warranty replacement.  
Thanks dude.

Peace,
- Trevor Martin

-- 
Trevelopment Trevor G Martin
Chief Technology Officer
Screenbid.com <http://screen.bid/Trez>
------------------------------------------------------------------------

**Comment by Siutsch** [comment]
I found  http://dillinger.io too and played around with it.

I modified README.md and AIO_FAQ.md a little bit and will use both for the future instead of the old txt files.
Again thank you for converting and helping me how to deal with GIT.
I'm learning from day to day! :)

And especially thanky you very much for the great http://mazdatweaks.com page.


For your problem with the CMU:
If your USB ports aren't working anymore, than I'm afraid there is no possibility to get access again to the system.
In this case I would go to the dealer and say, that this happens after doing a factory reset.
I don't think he is able to get the modified files or see, if the system was modded, so you should get a new CMU (hopefully).

**Comment by Trevelopment** [comment]
Hey,

I am also just learning GIT as I go along.  I have been doing web 
development for almost 10 years now but just started using git this year.

So after I get my CMU replaced, I am going to start development on a 
boot loader, so I may need your help with development a little bit. I 
don't have a lot of experience with BIOS or low level programming 
languages but I do have a grasp on the whole concept.  Plus, I'm one who 
enjoys a challenge and really hates when I can't fix a problem. So any 
knowledge you can bring to the table about the 
configuration/structure/architecture of the system I would appreciate it.
I am currently in the early stages of my research phase and I have yet 
to find anyone who has tried to do this yet.   I'm pretty sure you are 
right about the dealer not being able to tell that the system was modded 
but my car is so new (2016 Mazda 3) I just got it about 3 months ago and 
I 'm about to take it in for its very first scheduled maintenance 
(5000mi) so I definitely don't want to brick my second CMU after I 
bricked the first one so early.   If we can pull this off then the 
community and I will be extremely happy about it.
In the mean time, I will continue to make mazdatweaks.com better (though 
it is pretty sweet right now as is) and I will keep you updated on when 
I start the boot loader project. Thanks buddy, stay cool.

Peace,
- Trez

-- 
------------------------------------------------------------------------
Trevor@Trevelopment.com
Trevor G Martin
Chief Technology Officer
Screenbid.com <http://screen.bid/Trez>
------------------------------------------------------------------------

**Comment by Siutsch** [comment]
Although I have been programming since I was 15 years (near 30 years ago with Commodore C16!), I have no experience with "modern" programming languages, like C++, Java, or so.

That's the reason, why I made AIO with DOS Batch.
Nevertheless, I am happy and also surprised what can be done with that.

But I'm not a professional programmer and my knowledge about the configuration/structure/architecture of the system is very low.
Of course, I have learned a lot in the last 6 months, partly because of such helpful people, like you, but I'm afraid that I can't help you that much.
Of course, I'll try, as best I can! :)

Do you know of [this thread](http://mazda3revolution.com/forums/2014-2016-mazda-3-skyactiv-audio-electronics/123882-custom-applications-sdk-write-deploy-your-own-applications.html) by flyandi?
He is working on a Custom Applications SDK for the MZD and I think he is much deeper in the topic.

He is here too:
https://github.com/flyandi/mazda-custom-application-sdk

And apologize for my probably not always so great English, the whole thing here is also the way to improve this for me, but without google translator, i would be lost.  ;)

**Pull request merged**
