### PR TITLE
Some Tweak Fixes

### PR DESCRIPTION
**Pull request by Trevelopment**
Mostly log messages.  In 06d it was using the backup file AND copying
the file from USB.  It only needs to do one or the other. Small fix (Put
back becasue I took it out) hide speedo in statusbar while speedometer
is open because it makes the speedometer lag a little.

### CODE REVIEW

**Comment by Trevelopment** [comment]
## I have another fix to add as well 
**On line 3 in 02_03d.txt change:**
```js
cp -a ${MYDIR}/config_org/safety-warning-reverse-camera/jci/nativegui/images/*.png /jci/nativegui/images/
```
_to:_
```js
cp -a ${MYDIR}/config_org_all/safety-warning-reverse-camera/jci/nativegui/images/*.png /jci/nativegui/images/
```
I'm testing things out AIO 2.0.0 is coming along.

**Comment by Trevelopment** [comment]
### You may just want to do a ctrl + f for _/config_org/_ and replace with _/config_org_all/_ in all your uninstall files.

**Comment by Trevelopment** [comment]
# Or might be easier to just change the folder name back to _config_org_?

**Comment by Siutsch** [comment]
config_org is correct.

 

The folder is named "config_org" on the usb drive, if you uninstall.

 

Or is it, because yoe need that changes for AIO 2.0?

 

Please check Skype.

I wrote to you.
 

(\/)ª®©.

 
 

Gesendet: Freitag, 07. Oktober 2016 um 09:30 Uhr
Von: Trezdog44 <notifications@github.com>
An: Siutsch/AIO---All-in-one-tweaks <AIO---All-in-one-tweaks@noreply.github.com>
Betreff: Re: [Siutsch/AIO---All-in-one-tweaks] Some Tweak Fixes (#17)


You may just want to do a ctrl + f for /config_org/ and replace with /config_org_all/ in all your uninstall files.

**Comment by Trevelopment** [comment]
#### but those other little changes are good

**Comment by Siutsch** [comment]
Thanks.

**Comment by Siutsch** [comment]
New try

**Pull request closed without merging**
