### PR TITLE
Trezdog44: Added BackgroundRotator

### PR DESCRIPTION
**Pull request by Trevelopment**
Added Background Rotator Tweak - Trevelopment By Trezdog44

### CODE REVIEW

**Comment by Trevelopment** [comment]
Good stuff!

**Comment by Siutsch** [comment]
Thanks! :)

**Comment by Siutsch** [comment]
Hi.
Can you please take a look at the installer of your tweak at new AIO version 1.49?

It isn't working.

Have I done something wrong?

Thanks,
Siutsch.

**Comment by Trevelopment** [comment]
Hey I actually noticed this a few days ago but I thought you might catch 
it.  There needs to be trailing /s on the cp commands.
cp -a 
${MYDIR}/config/BackgroundRotator/jci/gui/common/images/background.png 
/jci/gui/common/images/
cp -a ${MYDIR}/config/BackgroundRotator/jci/gui/css/common.css 
/jci/gui/common/css/

On another note I was messing around with all kinds of files via ssh, 
like a smart guy, and I did make a backup of each file I edited but 
somehow I got into a boot loop situation. It was working fine after I 
rebooted but then I tried to reinstall the video player with the most 
recent AIO installer and after that all I got was the Mazda logo.  i 
checked and I'm petty sure I didn't edit any conflicting files... except 
maybe opera.ini. I think that may be the culprit. Anyways if you have 
any advice let me know.  or ill just wait for my adapter and then ping 
the shit out of my system.

Thanks,
~Trez


On 7/2/2016 9:01 AM, Siutsch wrote:
>
> Hi.
> Can you please take a look at the installer of your tweak at new AIO 
> version 1.49?
>
> It isn't working.
>
> Have I done something wrong?
>
> Thanks,
> Siutsch.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub 
> <https://github.com/Siutsch/AIO---All-in-one-tweaks/pull/1#issuecomment-230108773>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AJMQRFgkUGkEet4LXqnBzotBQ2W6LSMpks5qRos9gaJpZM4I6UFd>.
>

- Trevor Martin

-- 
------------------------------------------------------------------------
Screenbid
Trevor G Martin
Chief Technology Officer
Screenbid.com
8569 Higuera Street
Culver City, California 90232
(O) 310 287 0100 Ext 203
(M) 310 918 1289
------------------------------------------------------------------------

**Comment by Siutsch** [comment]
Hi.

I don't think, that is the problem, I use the copy command with or 
without last / and both ways work.

Could it be, that there has to be another *.js file, that has to be 
changed too?


Sorry to hear that you ran into a boot loop.

Is it a real boot loop or do you just see the Mazda logo animation all 
the time?

I hope it was not the fault of AIO, but I use it very often for 4 months 
now to test everyhing hundet of times and never had a boot loop.

Siutsch.



Am 02.07.2016 um 18:38 schrieb Trevor Martin:
> Hey I actually noticed this a few days ago but I thought you might catch
> it. There needs to be trailing /s on the cp commands.
> cp -a
> ${MYDIR}/config/BackgroundRotator/jci/gui/common/images/background.png
> /jci/gui/common/images/
> cp -a ${MYDIR}/config/BackgroundRotator/jci/gui/css/common.css
> /jci/gui/common/css/
>
> On another note I was messing around with all kinds of files via ssh,
> like a smart guy, and I did make a backup of each file I edited but
> somehow I got into a boot loop situation. It was working fine after I
> rebooted but then I tried to reinstall the video player with the most
> recent AIO installer and after that all I got was the Mazda logo. i
> checked and I'm petty sure I didn't edit any conflicting files... except
> maybe opera.ini. I think that may be the culprit. Anyways if you have
> any advice let me know. or ill just wait for my adapter and then ping
> the shit out of my system.
>
> Thanks,
> ~Trez
>
>
> On 7/2/2016 9:01 AM, Siutsch wrote:
> >
> > Hi.
> > Can you please take a look at the installer of your tweak at new AIO
> > version 1.49?
> >
> > It isn't working.
> >
> > Have I done something wrong?
> >
> > Thanks,
> > Siutsch.
> >
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly, view it on GitHub
> > 
> <https://github.com/Siutsch/AIO---All-in-one-tweaks/pull/1#issuecomment-230108773>, 
>
> > or mute the thread
> > 
> <https://github.com/notifications/unsubscribe/AJMQRFgkUGkEet4LXqnBzotBQ2W6LSMpks5qRos9gaJpZM4I6UFd>.
> >
>
> - Trevor Martin
>
> -- 
> ------------------------------------------------------------------------
> Screenbid
> Trevor G Martin
> Chief Technology Officer
> Screenbid.com
> 8569 Higuera Street
> Culver City, California 90232
> (O) 310 287 0100 Ext 203
> (M) 310 918 1289
> ------------------------------------------------------------------------
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub 
> <https://github.com/Siutsch/AIO---All-in-one-tweaks/pull/1#issuecomment-230110574>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AQLFDd9UXeI6QJusbrSlSQPESU9x2EHbks5qRpPogaJpZM4I6UFd>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by Trevelopment** [comment]
Oh yeah don't worry I know it was something I did. But I am just stuck 
on the Mazda logo animation all the time is there an easier way to 
recover from that?

and I think I see the error is in the path to common.css
  cp -a ${MYDIR}/config/BackgroundRotator/jci/gui/css/common.css 
/jci/gui/common/css/
should be:
  cp -a ${MYDIR}/config/BackgroundRotator/jci/gui/common/css/common.css 
/jci/gui/common/css/

~Trez

On 7/2/2016 11:36 AM, Siutsch wrote:
> Hi.
>
> I don't think, that is the problem, I use the copy command with or
> without last / and both ways work.
>
> Could it be, that there has to be another *.js file, that has to be
> changed too?
>
>
> Sorry to hear that you ran into a boot loop.
>
> Is it a real boot loop or do you just see the Mazda logo animation all
> the time?
>
> I hope it was not the fault of AIO, but I use it very often for 4 months
> now to test everyhing hundet of times and never had a boot loop.
>
> Siutsch.
>
>
>
> Am 02.07.2016 um 18:38 schrieb Trevor Martin:
> > Hey I actually noticed this a few days ago but I thought you might catch
> > it. There needs to be trailing /s on the cp commands.
> > cp -a
> > ${MYDIR}/config/BackgroundRotator/jci/gui/common/images/background.png
> > /jci/gui/common/images/
> > cp -a ${MYDIR}/config/BackgroundRotator/jci/gui/css/common.css
> > /jci/gui/common/css/
> >
> > On another note I was messing around with all kinds of files via ssh,
> > like a smart guy, and I did make a backup of each file I edited but
> > somehow I got into a boot loop situation. It was working fine after I
> > rebooted but then I tried to reinstall the video player with the most
> > recent AIO installer and after that all I got was the Mazda logo. i
> > checked and I'm petty sure I didn't edit any conflicting files... except
> > maybe opera.ini. I think that may be the culprit. Anyways if you have
> > any advice let me know. or ill just wait for my adapter and then ping
> > the shit out of my system.
> >
> > Thanks,
> > ~Trez
> >
> >
> > On 7/2/2016 9:01 AM, Siutsch wrote:
> > >
> > > Hi.
> > > Can you please take a look at the installer of your tweak at new AIO
> > > version 1.49?
> > >
> > > It isn't working.
> > >
> > > Have I done something wrong?
> > >
> > > Thanks,
> > > Siutsch.
> > >
> > > —
> > > You are receiving this because you modified the open/close state.
> > > Reply to this email directly, view it on GitHub
> > >
> > 
> <https://github.com/Siutsch/AIO---All-in-one-tweaks/pull/1#issuecomment-230108773>, 
>
> >
> > > or mute the thread
> > >
> > 
> <https://github.com/notifications/unsubscribe/AJMQRFgkUGkEet4LXqnBzotBQ2W6LSMpks5qRos9gaJpZM4I6UFd>.
> > >
> >
> > - Trevor Martin
> >
> > --
> > ------------------------------------------------------------------------
> > Screenbid
> > Trevor G Martin
> > Chief Technology Officer
> > Screenbid.com
> > 8569 Higuera Street
> > Culver City, California 90232
> > (O) 310 287 0100 Ext 203
> > (M) 310 918 1289
> > ------------------------------------------------------------------------
> >
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly, view it on GitHub
> > 
> <https://github.com/Siutsch/AIO---All-in-one-tweaks/pull/1#issuecomment-230110574>, 
>
> > or mute the thread
> > 
> <https://github.com/notifications/unsubscribe/AQLFDd9UXeI6QJusbrSlSQPESU9x2EHbks5qRpPogaJpZM4I6UFd>.
> >
>
>
>
> ---
> Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
> https://www.avast.com/antivirus
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub 
> <https://github.com/Siutsch/AIO---All-in-one-tweaks/pull/1#issuecomment-230115888>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AJMQRMGTyBv4e3Qot22uA8-_qugG27iFks5qRq-UgaJpZM4I6UFd>.
>

- Trevor Martin

-- 
------------------------------------------------------------------------
Screenbid
Trevor G Martin
Chief Technology Officer
Screenbid.com
8569 Higuera Street
Culver City, California 90232
(O) 310 287 0100 Ext 203
(M) 310 918 1289
------------------------------------------------------------------------

**Comment by Siutsch** [comment]
Ah, yes, I'm blind!

If you stuck on the Mazda Logo, then it isn't a boot loop.

Thy system isn't booting competely to an end, so the only thing you see 
is the never ending Mazda boot loop.

In this case there is good chance, that the USB ports are still working, 
so you can use USB drives to make jobs.
I think it has to to with a corrup cm.conf or opera.ini

If you have the original files, then you can change them.
If you used AIO before, then there has to be backups of these files (*.org).

If you have konfigured your WLAN settings before and had access to a 
WLAn access point, than SSH should still work.

But if you had AA installe before and if you had done a factory reset, 
then I'm afraid, you bricked your CMU.  :(



Am 02.07.2016 um 20:50 schrieb Trevor Martin:
> Oh yeah don't worry I know it was something I did. But I am just stuck
> on the Mazda logo animation all the time is there an easier way to
> recover from that?
>
> and I think I see the error is in the path to common.css
> cp -a ${MYDIR}/config/BackgroundRotator/jci/gui/css/common.css
> /jci/gui/common/css/
> should be:
> cp -a ${MYDIR}/config/BackgroundRotator/jci/gui/common/css/common.css
> /jci/gui/common/css/
>
> ~Trez
>
> On 7/2/2016 11:36 AM, Siutsch wrote:
> > Hi.
> >
> > I don't think, that is the problem, I use the copy command with or
> > without last / and both ways work.
> >
> > Could it be, that there has to be another *.js file, that has to be
> > changed too?
> >
> >
> > Sorry to hear that you ran into a boot loop.
> >
> > Is it a real boot loop or do you just see the Mazda logo animation all
> > the time?
> >
> > I hope it was not the fault of AIO, but I use it very often for 4 months
> > now to test everyhing hundet of times and never had a boot loop.
> >
> > Siutsch.
> >
> >
> >
> > Am 02.07.2016 um 18:38 schrieb Trevor Martin:
> > > Hey I actually noticed this a few days ago but I thought you might 
> catch
> > > it. There needs to be trailing /s on the cp commands.
> > > cp -a
> > > ${MYDIR}/config/BackgroundRotator/jci/gui/common/images/background.png
> > > /jci/gui/common/images/
> > > cp -a ${MYDIR}/config/BackgroundRotator/jci/gui/css/common.css
> > > /jci/gui/common/css/
> > >
> > > On another note I was messing around with all kinds of files via ssh,
> > > like a smart guy, and I did make a backup of each file I edited but
> > > somehow I got into a boot loop situation. It was working fine after I
> > > rebooted but then I tried to reinstall the video player with the most
> > > recent AIO installer and after that all I got was the Mazda logo. i
> > > checked and I'm petty sure I didn't edit any conflicting files... 
> except
> > > maybe opera.ini. I think that may be the culprit. Anyways if you have
> > > any advice let me know. or ill just wait for my adapter and then ping
> > > the shit out of my system.
> > >
> > > Thanks,
> > > ~Trez
> > >
> > >
> > > On 7/2/2016 9:01 AM, Siutsch wrote:
> > > >
> > > > Hi.
> > > > Can you please take a look at the installer of your tweak at new AIO
> > > > version 1.49?
> > > >
> > > > It isn't working.
> > > >
> > > > Have I done something wrong?
> > > >
> > > > Thanks,
> > > > Siutsch.
> > > >
> > > > —
> > > > You are receiving this because you modified the open/close state.
> > > > Reply to this email directly, view it on GitHub
> > > >
> > >
> > 
> <https://github.com/Siutsch/AIO---All-in-one-tweaks/pull/1#issuecomment-230108773>, 
>
> >
> > >
> > > > or mute the thread
> > > >
> > >
> > 
> <https://github.com/notifications/unsubscribe/AJMQRFgkUGkEet4LXqnBzotBQ2W6LSMpks5qRos9gaJpZM4I6UFd>.
> > > >
> > >
> > > - Trevor Martin
> > >
> > > --
> > > 
> ------------------------------------------------------------------------
> > > Screenbid
> > > Trevor G Martin
> > > Chief Technology Officer
> > > Screenbid.com
> > > 8569 Higuera Street
> > > Culver City, California 90232
> > > (O) 310 287 0100 Ext 203
> > > (M) 310 918 1289
> > > 
> ------------------------------------------------------------------------
> > >
> > > —
> > > You are receiving this because you modified the open/close state.
> > > Reply to this email directly, view it on GitHub
> > >
> > 
> <https://github.com/Siutsch/AIO---All-in-one-tweaks/pull/1#issuecomment-230110574>, 
>
> >
> > > or mute the thread
> > >
> > 
> <https://github.com/notifications/unsubscribe/AQLFDd9UXeI6QJusbrSlSQPESU9x2EHbks5qRpPogaJpZM4I6UFd>.
> > >
> >
> >
> >
> > ---
> > Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
> > https://www.avast.com/antivirus
> >
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly, view it on GitHub
> > 
> <https://github.com/Siutsch/AIO---All-in-one-tweaks/pull/1#issuecomment-230115888>, 
>
> > or mute the thread
> > 
> <https://github.com/notifications/unsubscribe/AJMQRMGTyBv4e3Qot22uA8-_qugG27iFks5qRq-UgaJpZM4I6UFd>.
> >
>
> - Trevor Martin
>
> -- 
> ------------------------------------------------------------------------
> Screenbid
> Trevor G Martin
> Chief Technology Officer
> Screenbid.com
> 8569 Higuera Street
> Culver City, California 90232
> (O) 310 287 0100 Ext 203
> (M) 310 918 1289
> ------------------------------------------------------------------------
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub 
> <https://github.com/Siutsch/AIO---All-in-one-tweaks/pull/1#issuecomment-230116517>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AQLFDRfhMh-VtxtnL6bc4HN_fMYljIxcks5qRrMKgaJpZM4I6UFd>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by Trevelopment** [comment]
So I am stuck on the logo and I didn't have AA installed (I'm sure you 
warned me not to do that at some point). I don't know if the USB ports 
are working but I tried a simple .sh that would just change one file 
then reboot but I don't think it was working, though I don't quite have 
a full understanding of the system.  And as for the WLAN settings, I had 
to turn the wifi on every time I turned the system on, so I'm going to 
order the Ethernet to USB adapter with the correct chipset to hookup to 
the USB port.  If you have any scripts/advice or anything that would be 
greatly appreciated. Hopefully I didn't brick my system though it is 
under warranty, I don't want them to see all my mods and not replace it.

I had one question about watchdog, is it permanently disabled so the 
system can't end up in a true boot loop (where the system reboots on 
error)? and does it need to be disabled every time you mount -o rw?

So I ended up in  a boot loop such that the system is unable to fully 
boot up?

And I really appreciate all your time you take to help me out.


Thanks Buddy,

~Trez

**Comment by Trevelopment** [comment]
So I am stuck on the logo and I didn't have AA installed (I'm sure you 
warned me not to do that at some point). I don't know if the USB ports 
are working but I tried a simple .sh that would just change one file 
then reboot but I don't think it was working, though I don't quite have 
a full understanding of the system.  And as for the WLAN settings, I had 
to turn the wifi on every time I turned the system on, so I'm going to 
order the Ethernet to USB adapter with the correct chipset to hookup to 
the USB port.  If you have any scripts/advice or anything that would be 
greatly appreciated. Hopefully I didn't brick my system though it is 
under warranty, I don't want them to see all my mods and not replace it.

I had one question about watchdog, is it permanently disabled so the 
system can't end up in a true boot loop (where the system reboots on 
error)? and does it need to be disabled every time you mount -o rw?

So I ended up in  a boot loop such that the system is unable to fully 
boot up?

And I really appreciate all your time you take to help me out.


Thanks Buddy,

~Trez

**Pull request closed without merging**
